version: "3"

services:
  go-server:
    image: go-server:latest
    build: "."
    ports:
      - "8080:8080"
    restart: always
  nginx:
    image: nginx:1.18
    container_name: nginx
    volumes:
      - ./nginx:/usr/share/nginx/html
      # - ./nginx/default.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - go-server
