version: "3"

services:
  go_server:
    image: go_server:latest
    build: "."
    ports:
      - "8080:8080"
      - "2112:2112"
    networks:
      - my-network
    restart: always
  nginx:
    image: nginx:1.18
    container_name: nginx
    volumes:
      - ./nginx:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - go_server
    restart: always
  prometheus:
    image: prom/prometheus:v2.24.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    restart: always
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "9080:9080"
  #   volumes:
  #     - grafana-storage:/var/lib/grafana

networks:
  my-network:
    driver: bridge

volumes:
  grafana-storage:
  prometheus_data:
