// Code generated by MockGen. DO NOT EDIT.
// Source: ./mock/sns_mock/IMock_Sns.go

// Package mocks is a generated GoMock package.
package sns_mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockISnsMockInterface is a mock of ISnsMockInterface interface.
type MockISnsMockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockISnsMockInterfaceMockRecorder
}

// MockISnsMockInterfaceMockRecorder is the mock recorder for MockISnsMockInterface.
type MockISnsMockInterfaceMockRecorder struct {
	mock *MockISnsMockInterface
}

// NewMockISnsMockInterface creates a new mock instance.
func NewMockISnsMockInterface(ctrl *gomock.Controller) *MockISnsMockInterface {
	mock := &MockISnsMockInterface{ctrl: ctrl}
	mock.recorder = &MockISnsMockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISnsMockInterface) EXPECT() *MockISnsMockInterfaceMockRecorder {
	return m.recorder
}

// NewPost mocks base method.
func (m *MockISnsMockInterface) NewPost(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewPost", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// NewPost indicates an expected call of NewPost.
func (mr *MockISnsMockInterfaceMockRecorder) NewPost(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewPost", reflect.TypeOf((*MockISnsMockInterface)(nil).NewPost), arg0)
}
