// Code generated by sqlc. DO NOT EDIT.
// source: comment_query.sql

package sns_mysql

import (
	"context"
	"database/sql"
)

const createNewComment = `-- name: CreateNewComment :execresult
INSERT INTO comment (
    post_id,
    comment_owner_account,
    text
) VALUES (
   ?, ?, ?
)
`

type CreateNewCommentParams struct {
	PostID              int32  `json:"post_id"`
	CommentOwnerAccount string `json:"comment_owner_account"`
	Text                string `json:"text"`
}

func (q *Queries) CreateNewComment(ctx context.Context, arg CreateNewCommentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createNewComment, arg.PostID, arg.CommentOwnerAccount, arg.Text)
}

const deleteComment = `-- name: DeleteComment :execresult
DELETE FROM comment 
WHERE comment_id = ? LIMIT 1
`

func (q *Queries) DeleteComment(ctx context.Context, commentID int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteComment, commentID)
}
