name: my-ci

on: push

jobs:
  go-version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Display Go version
        run: go version

      - name: Download Dependencies
        run: go mod download

      - name: build go File
        run: go build

  lint-go-action:
    strategy:
      matrix:
        go: [1.20]
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.17"
          cache: false
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
