name: my-ci

on: push

jobs:
  go-version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Display Go version
        run: go version

      - name: Download Dependencies
        run: go mod download

  lint-go-action:
    strategy:
      matrix:
        go: [1.20]
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
      - uses: actions/checkout@v3
        with:
          stable: "false"
          go-version: "1.20"
          cache: false
      - name: golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest

          golangci-lint run
