name: pull-requeest-lint

on:
  pull_request:

jobs:
  lint-check:
    strategy:
      matrix:
        go: [1.20]
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
        with:
          go-version: "1.20"
          cache: false
          ref: ${{ github.event.pull_request.head.sha }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: "--timeout 5m"
