name: pull-requeest-lint

on:
  pull_request:

jobs:
  lint-check:
    strategy:
      matrix:
        go: [1.20]
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
      - uses: actions/checkout@v3
        with:
          stable: "false"
          go-version: "1.20"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: "--timeout 10m"

      - name: Testing Go Code
        run: go test -v ./...
